---
- name: Clone Zidisha repository
  git: dest=/workspace/zidisha repo={{ git.repository }} update=no

- name: Copy the constants.php file
  template: src=../../../..{{ paths.root }}library/constant_local.php dest={{ paths.root }}library/constant.php mode=0644 force=no

- name: Create the zidisha_contents directory
  file: path=/workspace/zidisha.local/zidisha_contents state=directory mode=0777

- name: Symlink the app_logs into the zidisha_contents directory
  file: path=/workspace/zidisha.local/zidisha_contents/logs state=directory mode=0775 recurse=yes owner=www-data group=vagrant

- name: Create the Smarty cache directory
  sudo: yes
  file: path=/workspace/zidisha.local/extlibs/smarty/{{ item }} mode=0775 state=directory recurse=yes owner=www-data group=vagrant
  with_items:
      - templates_c
      - cache