---
- name: Install required packages
  apt: pkg={{ item }} update_cache=yes
  sudo: yes
  with_items:
    - apache2
    - libapache2-mod-php5
    - php5
    - php5-dev
    - php5-mysql
    - php-apc
    - php5-xdebug
    - php5-curl
    - php5-json
    - php-pear
    - sendmail

- name: Create the php.ini file
  sudo: yes
  template: src=php.ini.j2 dest=/etc/php5/apache2/php.ini owner=root group=root mode=0644
  notify: Restart Apache

- name: Enable rewrite module
  sudo: yes
  command: a2enmod rewrite expires

- name: Create the logging directory
  file: path={{ item }} owner=www-data group=www-data state=directory
  sudo: yes
  with_items:
      - /var/log/zidisha.local
      - /var/log/zidisha.local/app_logs
      - /var/log/zidisha.local/apache2


- name: Copy the virtualhost to the sites-available directory
  sudo: yes
  template: src=zidisha.local.conf.j2 dest=/etc/apache2/sites-available/zidisha.local.conf

- name: Enable the virtualhost
  sudo: yes
  command: a2ensite zidisha.local.conf
  notify: Restart Apache

- name: Create the Apache group
  sudo: yes
  group: name={{ apache.group }}

- name: Create the Apache user
  sudo: yes
  user: name={{ apache.user }} group={{ apache.group }}

- name: Check the Apache group
  register: correct_apache_group
  command: grep -c 'APACHE_RUN_GROUP={{ apache.group }}' /etc/apache2/envvars
  ignore_errors: yes

- name: Change the Apache group
  sudo: yes
  command: sed -i 's/APACHE_RUN_GROUP=.*$/APACHE_RUN_GROUP={{ apache.group }}/' /etc/apache2/envvars
  when: correct_apache_group|failed
  notify: Restart Apache

- name: Check the Apache user
  register: correct_apache_user
  command: grep -c 'APACHE_RUN_USER={{ apache.user }}' /etc/apache2/envvars
  ignore_errors: yes

- name: Change the Apache user
  sudo: yes
  command: sed -i 's/APACHE_RUN_USER=.*$/APACHE_RUN_USER={{ apache.user }}/' /etc/apache2/envvars
  when: correct_apache_user|failed
  notify: Restart Apache
