---

- hosts: vagrant
  vars:
    apache:
        hostname: zidisha.dev
        user: vagrant
        group: vagrant
    php:
        error_reporting: E_ALL
        display_errors: On
        display_startup_errors: On
        error_log: /var/log/php_error.log
        date_timezone: America/New_York
        sendmail_path: "/usr/bin/env catchmail"
        sendmail_from: "service@zidisha.dev"
    git:
        repository: "https://github.com/Zidisha/zidisha.git"
    database:
        host: 127.0.0.1
        name: zidisha
        user: zidisha
        password: zidisha

  roles:
    - common
    - { role: perlmonkey.role-mailcatcher, sudo: yes }
    - database
    - webserver
    - zidisha
